# -*- encoding: utf-8 -*-

=begin
#videoapi

#The video APIs help you convert, encode, and transcode videos.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

$:.push File.expand_path("../lib", __FILE__)
require "cloudmersive-video-api-client/version"

Gem::Specification.new do |s|
  s.name        = "cloudmersive-video-api-client"
  s.version     = CloudmersiveVideoApiClient::VERSION
  s.platform    = Gem::Platform::RUBY
  s.authors     = ["Cloudmersive"]
  s.email       = [""]
  s.homepage    = "https://cloudmersive.com/video-and-media-services-api"
  s.summary     = "Convert API lets you effortlessly convert, process and encode video and media files."
  s.description = "Convert and encode video and media files and content between file formats. On-demand."
  s.license     = 'Apache 2.0'
  s.required_ruby_version = ">= 1.9"

  s.add_runtime_dependency 'typhoeus', '~> 1.0', '>= 1.0.1'
  s.add_runtime_dependency 'json', '~> 2.1', '>= 2.1.0'

  s.add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'
  s.add_development_dependency 'vcr', '~> 3.0', '>= 3.0.1'
  s.add_development_dependency 'webmock', '~> 1.24', '>= 1.24.3'
  s.add_development_dependency 'autotest', '~> 4.4', '>= 4.4.6'
  s.add_development_dependency 'autotest-rails-pure', '~> 4.1', '>= 4.1.2'
  s.add_development_dependency 'autotest-growl', '~> 0.2', '>= 0.2.16'
  s.add_development_dependency 'autotest-fsevent', '~> 0.2', '>= 0.2.12'

  s.files         = Dir['./**/*']
  s.test_files    = `find spec/*`.split("\n")
  s.executables   = []
  s.require_paths = ["lib"]
end
