=begin
#videoapi

#The video APIs help you convert, encode, and transcode videos.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for CloudmersiveVideoApiClient::VideoFile
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VideoFile' do
  before do
    # run before each test
    @instance = CloudmersiveVideoApiClient::VideoFile.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VideoFile' do
    it 'should create an instance of VideoFile' do
      expect(@instance).to be_instance_of(CloudmersiveVideoApiClient::VideoFile)
    end
  end
  describe 'test attribute "video_number"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "content"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
