=begin
#videoapi

#The video APIs help you convert, encode, and transcode videos.

OpenAPI spec version: v1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

# Common files
require 'cloudmersive-video-api-client/api_client'
require 'cloudmersive-video-api-client/api_error'
require 'cloudmersive-video-api-client/version'
require 'cloudmersive-video-api-client/configuration'

# Models
require 'cloudmersive-video-api-client/models/media_information'
require 'cloudmersive-video-api-client/models/nsfw_result'
require 'cloudmersive-video-api-client/models/nsfw_scanned_frame'
require 'cloudmersive-video-api-client/models/split_video_result'
require 'cloudmersive-video-api-client/models/still_frame'
require 'cloudmersive-video-api-client/models/still_frames_result'
require 'cloudmersive-video-api-client/models/video_file'

# APIs
require 'cloudmersive-video-api-client/api/audio_api'
require 'cloudmersive-video-api-client/api/video_api'

module CloudmersiveVideoApiClient
  class << self
    # Customize default settings for the SDK using block.
    #   CloudmersiveVideoApiClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
